### ISSUE TITLE
Override of provider url when running locally barge and ocean-node on macOs

### ISSUE THREAD

**Issue by FilipMasar** [oceanprotocol/ocean-cli#46]
**Describe the bug**
There is this hardcoded provider url for macOs https://github.com/oceanprotocol/ocean-cli/blob/main/src/commands.ts#L41
It was added in [this commit](https://github.com/oceanprotocol/ocean-cli/commit/7b1bf45af825de6326f79391af5bde6224cdb602). Why is that needed?

I am running ocean-node on port `8000` and exporting `export PROVIDER_URL='http://127.0.0.1:8000'`. But this block of code will override it.

**Comment by bogdanfazakas** [comment]
This is needed because ocean.js will export the provider url with the barge subnet url, that on macOS (same issue if running barge in docker desktop app) is unreachable, so we always have to use `http://127.0.0.1:8030` instead of  `http://172.15.0.4:8030`. Will fix this so if the env var is set this would not be set, because forcing a url by setting the env var of Provider or Aquarius url should have the higher priority in terms of usage.
